[versions]
kotlin = "2.1.20"
compose = "1.8.0"
ktlintPlugin = "14.0.1"
junit = "5.10.2"
detekt = "1.23.6"
sqldelight = "2.0.2"
slf4j = "2.0.13"
pdfbox = "3.0.2"
coroutines = "1.8.1"
serialization = "1.7.1"
okio = "3.9.0"
sqliteJdbc = "3.46.1.3"

[libraries]
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
sqldelight-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
